FROM ubuntu:22.04

RUN apt-get update && \
    apt-get upgrade --yes

RUN apt-get install --yes \
      apt-transport-https \
      bridge-utils \
      curl \
      dnsutils \
      gpg \
      jq \
      mtr \
      netcat \
      tcpdump \
      telnet \
      traceroute \
      wget
