#!/bin/bash
docker run --rm \
  --volume $PWD:/app \
  --volume ~/.gitconfig:/etc/gitconfig \
  --user $(id -u) \
  commitizen/commitizen:latest \
    bump \
      --changelog \
      --annotated-tag-message "original-commit-sha: $(git rev-parse HEAD)"

git show 0.7.0 \
  --pretty="%N" \
  --no-patch \
| grep "original-commit-sha:" \
| awk '{ print $2 }'
