#!/bin/bash
echo
echo "1. Build"
echo

docker build -t mongoshell .

echo
echo "2. Default"
echo

docker run \
  --rm \
  --env MONGODB_HOST=${MONGODB_HOST?} \
  --env MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME?} \
  --env MONGODB_USERNAME=${MONGODB_USERNAME?} \
  --env MONGODB_PASSWORD=${MONGODB_PASSWORD?} \
  mongoshell:latest \
    --debug 1

echo
echo "3. Custom command"
echo

docker run \
  --rm \
  --env MONGODB_HOST=${MONGODB_HOST?} \
  --env MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME?} \
  --env MONGODB_USERNAME=${MONGODB_USERNAME?} \
  --env MONGODB_PASSWORD=${MONGODB_PASSWORD?} \
  mongoshell:latest \
    --command 'printjson(db.accounts.find( { "account_id": 702610 } ))'

export MONGODB_PASSWORD_URL_ENCODED=$(printf %s "${MONGODB_PASSWORD?}" | jq -sRr @uri)
export MONGODB_CONNECTION_STRING="mongodb+srv://${MONGODB_USERNAME?}:${MONGODB_PASSWORD_URL_ENCODED}@${MONGODB_HOST?}/${MONGODB_DATABASE_NAME?}?readPreference=secondaryPreferred&readPreferenceTags=workloadType:OPERATIONAL&retryWrites=true&w=majority&maxStalenessSeconds=90&maxIdleTimeMS=1500000&appName=mongoshell&minPoolSize=10"

echo
echo "4. Connection string"
echo

docker run \
  --rm \
  --env MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING?} \
  mongoshell:latest

echo
echo "5. TCP Ping"
echo

docker run \
  --rm \
  --entrypoint /opt/scripts/tcpping \
  mongoshell:latest \
    -d -x 5 google.com 443
