#!/bin/bash
WORK_DIRECTORY="${WORK_DIRECTORY:-/tmp/work}"

# Create a temporary work directory
mkdir -p "${WORK_DIRECTORY?}"

# Docker socket file
DOCKER_SOCKET_FILE="/var/run/docker.sock"
DOCKER_SOCKET_GID=$(stat -c %g ${DOCKER_SOCKET_FILE?})

# Container user and group
CONTAINER_USER_ID=1001
CONTAINER_GROUP_ID=${DOCKER_SOCKET_GID?}

# Change the temporary work directory group
chown :${CONTAINER_GROUP_ID?} "${WORK_DIRECTORY?}"

# Allow the container to access the temporary work directory
chmod 775 "${WORK_DIRECTORY?}"

declare -A COMMANDS
COMMANDS[0]="--rm"
COMMANDS[1]="--user ${CONTAINER_USER_ID?}:${CONTAINER_GROUP_ID?}"
COMMANDS[2]="--volume ${DOCKER_SOCKET_FILE?}:${DOCKER_SOCKET_FILE?}"
COMMANDS[3]="--volume ${WORK_DIRECTORY?}:${WORK_DIRECTORY?}"
COMMANDS[4]="--group-add ${DOCKER_SOCKET_GID?}"

if [ -t 1 ]; then
  COMMANDS[5]="--interactive"
  COMMANDS[6]="--tty"
fi

INPUT_COMMANDS=${@}

docker run ${COMMANDS[@]} ${INPUT_COMMANDS[@]}
