#!/bin/bash
work_directory="${WORK_DIRECTORY:-/tmp/work}"

# Create the work directory if it does not exist
mkdir --parents "${work_directory?}"

# Docker socket file
docker_socket_file="/var/run/docker.sock"
docker_socket_group_id=$(stat --format "%g" ${docker_socket_file?})

# Container user and group
container_user_id=1001
container_group_id=${docker_socket_group_id?}

# Change the work directory group
chown :${container_group_id?} "${work_directory?}"

# Change work directory to be read, write and accessible by the group members
chmod g+rwx "${work_directory?}"

arguments=()
arguments+=("--rm")
arguments+=("--user ${container_user_id?}:${container_group_id?}")
arguments+=("--env WORK_DIRECTORY=${work_directory?}")
arguments+=("--volume ${docker_socket_file?}:${docker_socket_file?}")
arguments+=("--volume ${work_directory?}:${work_directory?}")
arguments+=("--group-add ${container_group_id?}")

if [[ -t 1 ]]; then
  arguments+=("--interactive")
  arguments+=("--tty")
fi

input_arguments=()
for input_argument in ${@}; do
  input_arguments+=("${input_argument}")
done

if [[ ${#input_arguments[@]} -eq 0 ]]; then
  arguments+=("runner")
  arguments+=("hello")
fi

docker run ${arguments[@]} ${input_arguments[@]}
