#!/bin/bash
# Show user and group information
id
echo ""

# Generate an execution ID in the format: YYYY-MM-DD_HH-MM-SS.nnn
EXECUTION_ID=$(date +"%Y-%m-%d_%H-%M-%S.%3N")

# Create directories
TEMPORARY_DIRECTORY="/tmp/work/${EXECUTION_ID?}"
LOGS_DIRECTORY="${TEMPORARY_DIRECTORY?}/logs"
mkdir -p "${TEMPORARY_DIRECTORY?}"
mkdir -p "${LOGS_DIRECTORY?}"

# Create a file and copy it
HELLO_FILE_FIRST="${TEMPORARY_DIRECTORY?}/hello.txt"
HELLO_FILE_SECOND="${LOGS_DIRECTORY?}/hello.txt"

cat <<EOF > "${HELLO_FILE_FIRST?}"
Hello, world!
EOF

cp "${HELLO_FILE_FIRST?}" "${HELLO_FILE_SECOND?}"

# Show files and permissions
echo "${TEMPORARY_DIRECTORY?}"
find "${TEMPORARY_DIRECTORY?}" -type f -exec ls -lh {} \;
echo ""

# Try to run a Docker container
ls -lh /var/run/docker.sock
echo ""
docker run --rm hello-world | grep --extended-regexp "^This message"
