#!/bin/bash
# Show user and group information
echo "user:"
id
echo ""

# Show umask value as human readable
echo "umask:"
umask -S
echo ""

# Generate an execution ID in the format: YYYY-MM-DD_HH-MM-SS.nnn
execution_id=$(date +"%M%S.%3N")

# Create directories
temporary_directory="${WORK_DIRECTORY:-/tmp/work}/${execution_id?}"
logs_directory="${temporary_directory?}/logs"
mkdir --parents "${temporary_directory?}"
mkdir --parents "${logs_directory?}"

# Create a file and copy it
hello_source="${temporary_directory?}/hello.txt"
hello_target="${logs_directory?}/hello.txt"

cat <<EOF > "${hello_source?}"
Hello, world!
EOF

cp "${hello_source?}" "${hello_target?}"

# Show files and permissions
echo "${temporary_directory?}:"
find "${temporary_directory?}" -type f -exec ls -lh {} \;
echo ""

docker_socket="/var/run/docker.sock"

if [[ -e ${docker_socket} ]]; then
  echo "docker:"
  ls -lh ${docker_socket}
  echo ""
  docker run --rm hello-world | grep --extended-regexp "^This message"
  echo ""
fi
