name: ci-example-build-and-push

on:
  push:
    branches:
      - main

    paths:
      - "ci-example/**"
      - ".github/workflows/**"
      - '!**/README.md'
      - '!**/CHANGELOG.md'
  
  workflow_dispatch:

jobs:
  build-and-push:
    if: "!startsWith(github.event.head_commit.message, 'bump')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: |
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV

          echo "GITHUB_REPOSITORY.: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA........: ${GITHUB_SHA}"
          echo "COMMIT_HASH.......: ${COMMIT_HASH}"

      - name: Build Docker image
        run: |
          DOCKER_IMAGE_NAME=ghcr.io/${{ github.repository }}:${COMMIT_HASH}

          echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}" >> $GITHUB_ENV

          echo "GITHUB_REPOSITORY.: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA........: ${GITHUB_SHA}"
          echo "COMMIT_HASH.......: ${COMMIT_HASH}"
          echo "DOCKER_IMAGE_NAME.: ${DOCKER_IMAGE_NAME}"

          docker build -t ${DOCKER_IMAGE_NAME} ./ci-example

      - name: Push Docker image
        run: |
          echo "GITHUB_REPOSITORY.: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA........: ${GITHUB_SHA}"
          echo "COMMIT_HASH.......: ${COMMIT_HASH}"
          echo "DOCKER_IMAGE_NAME.: ${DOCKER_IMAGE_NAME}"

          docker push ${DOCKER_IMAGE_NAME}

      - name: Bump version
        run: |
          echo "PWD...............: $PWD"
          echo "GITHUB_REPOSITORY.: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA........: ${GITHUB_SHA}"
          echo "COMMIT_HASH.......: ${COMMIT_HASH}"
          echo "DOCKER_IMAGE_NAME.: ${DOCKER_IMAGE_NAME}"

          echo "Trying to list tags..."
          git tag --list

          echo "Trying to show status..."
          git status

          if [ -f ~/.gitconfig ]; then
            echo "Found ~/.gitconfig"
            cat ~/.gitconfig
          else
            echo "No ~/.gitconfig found"
          fi

          echo "Trying to bump version..."

          docker run --rm \
            --volume $PWD:/app \
            --user $(id -u) \
            commitizen/commitizen:latest --debug \
              bump \
                --changelog \
                --annotated-tag-message "original-commit-sha: ${COMMIT_HASH?}"

          git push
          git push --tags
