name: ci-example-release-by-tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to release
        required: true
      environment:
        description: Environment to run tests against
        type: environment
        required: true
        default: continuos-integration

jobs:
  release:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
     
      - name: Log Triggered Tag
        env:
          TAG: ${{ inputs.tag }}
        run: |
          echo "GITHUB_REF....: ${GITHUB_REF}"
          echo "TAG...........: ${TAG}"

          git show ${TAG} \
            --pretty="%N" \
            --no-patch \
          | grep "original-commit-sha:" \
          | awk '{ print $2 }'
