name: ci-example-release-by-tag

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract previous commit hash
        id: previous-commit
        run: |
          CURRENT_COMMIT_HASH=${GITHUB_SHA}

          PREVIOUS_COMMIT_HASH=$(git rev-list --parents -n 1 ${GITHUB_SHA} | awk '{print $2}')
          
          echo "CURRENT_COMMIT_HASH..: ${CURRENT_COMMIT_HASH}"
          echo "PREVIOUS_COMMIT_HASH.: ${PREVIOUS_COMMIT_HASH}"

          echo "PREVIOUS_COMMIT_HASH=${PREVIOUS_COMMIT_HASH}" >> $GITHUB_ENV

      - name: Log Previous Commit Hash
        run: |
          echo "Previous commit hash is: ${{ env.PREVIOUS_COMMIT_HASH }}"

      - name: Update base image
        run: |
          # Exemplo de atualização de imagem base
          echo "Updating base image with new version..."
      
      - name: Log Triggered Tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}

          echo "GITHUB_REF....: ${GITHUB_REF}"
          echo "TAG_NAME......: ${TAG_NAME}"

          echo "The tag that triggered this workflow is: $TAG_NAME"
