name: Docker Image kubectl CI

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Bash script test
        run: |
          pwd
          find
        shell: bash

      - name: kubectl binary download
        shell: bash
        run: kubectl/donwload-binary.sh
 