name: sandbox

on:
  workflow_dispatch:

jobs:
  execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:          
          fetch-depth: 0
          path: repo

      - name: Runner Tests
        run: |
          repo/runner/run docker.io/silviosilva/runner:22.04 hello
